[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Multi-key header rules are expressed with multi-line strings
    Link = '''
    </assets/css/index.css>; rel=preload; as=style, \
    </assets/js/index.js>; rel=preload; as=script'''
    # Basic-Auth allows you to password protect your whole site but is only available
    # to paid accounts
    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"